#include "sd_card.h"
#include "fatfs.h"
#include "ff.h"
#include "fatfs_platform.h"
#include "recorder.h"
#include "player.h"
#include "FreeRTOS.h"
#include "semphr.h"
#include "task.h"
#include "stm32f7xx_hal.h"
#include <string.h>

/* SDFatFS, SDPath, retSD all live in FATFS/App/fatfs.c (generated by
   CubeMX). MX_FATFS_Init() has already called FATFS_LinkDriver() before
   we run, so f_mount can use the empty drive prefix immediately. */
extern FATFS SDFatFS;
extern char  SDPath[4];

/* hsd1 is the CubeMX-owned SDMMC HAL handle. We need it to call
   HAL_SD_Abort_IT() on card removal so any in-flight DMA returns
   immediately instead of waiting out SD_TIMEOUT. */
extern SD_HandleTypeDef hsd1;

static volatile bool      s_mounted;
static uint16_t           s_next_index;        /* next index for sd_card_next_filename */
static SemaphoreHandle_t  s_fatfs_mutex;       /* serializes all FATFS access */

/* Parse "RECNNN.WAV" → index, or return -1 if the name doesn't match.
   Lookups are case-sensitive against the uppercase form we always emit;
   FAT32 short-name entries are uppercased by the filesystem on write, so
   a freshly-written file always reads back uppercase. */
static int parse_rec_index(const char *name)
{
    if (name[0] != 'R' || name[1] != 'E' || name[2] != 'C') return -1;
    int idx = 0;
    int digits = 0;
    int i = 3;
    while (name[i] >= '0' && name[i] <= '9' && digits < 4) {
        idx = idx * 10 + (name[i] - '0');
        i++;
        digits++;
    }
    if (digits == 0) return -1;
    if (name[i] != '.') return -1;
    if (name[i+1] != 'W' || name[i+2] != 'A' || name[i+3] != 'V') return -1;
    if (name[i+4] != '\0') return -1;
    return idx;
}

/* Walk the root directory, track the highest REC index seen. Called at
   mount and from sd_card_next_filename() to pick the next slot. Caller
   MUST hold s_fatfs_mutex. */
static FRESULT scan_highest_index_locked(uint16_t *out_next)
{
    DIR  dir;
    FILINFO fno;
    int highest = 0;

    FRESULT r = f_opendir(&dir, "/");
    if (r != FR_OK) return r;

    for (;;) {
        r = f_readdir(&dir, &fno);
        if (r != FR_OK || fno.fname[0] == 0) break;
        if (fno.fattrib & AM_DIR) continue;
        int idx = parse_rec_index(fno.fname);
        if (idx > highest) highest = idx;
    }
    f_closedir(&dir);

    *out_next = (uint16_t)(highest + 1);
    return FR_OK;
}

/* Force HAL_SD back to a clean RESET state. Called before every mount
   attempt so we don't inherit leftover peripheral or handle state from a
   previous yank.

   Why this is necessary: HAL_SD_Abort_IT during removal leaves hsd1.State
   as READY (or BUSY if the async DMA-abort hadn't completed yet) — not
   RESET. The next HAL_SD_Init then skips its `if (state == RESET)` branch,
   meaning HAL_SD_MspInit is never re-called and the SDMMC1 clock/GPIO/DMA
   config isn't refreshed. Worse, the SDMMC1 peripheral itself can sit on
   stale register state from the aborted transfer (DCTRL data-enable bit,
   FIFO pointers, etc.). The card-init sequence inside HAL_SD_InitCard
   then fails silently — usually at CMD0 or CMD8 — and BSP_SD_Init returns
   MSD_ERROR. f_mount fails with FR_NOT_READY; sd_card_poll retries on the
   next 250 ms tick; each failed attempt burns ~50 ms of busy-wait inside
   SDMMC_CMDTIMEOUT loops at osPriorityNormal, starving the UI task at
   IDLE+1. User sees the UI freeze and the card stay undetected.

   The fix is to fully tear down HAL_SD between mount attempts: DeInit
   (state → RESET, MspDeInit disables clock/GPIO/DMA/NVIC) plus an RCC
   force-reset of SDMMC1 (clears register state the HAL doesn't touch).
   Next HAL_SD_Init then takes the state==RESET branch and re-runs MspInit
   from scratch.

   Guard with `hsd1.hdmarx != NULL`: at very first boot, MspInit has not
   run yet (CubeMX-generated MX_SDMMC1_SD_Init only fills the hsd1.Init
   struct without calling HAL_SD_Init), so hdmarx/hdmatx are NULL and
   HAL_SD_DeInit → HAL_DMA_DeInit(NULL) would fault. The flag lets boot
   pass through cleanly while every subsequent mount gets the reset. */
static void reset_sd_hal(void)
{
    if (hsd1.hdmarx == NULL) return;        /* first boot — nothing to reset */

    HAL_SD_DeInit(&hsd1);
    __HAL_RCC_SDMMC1_FORCE_RESET();
    __HAL_RCC_SDMMC1_RELEASE_RESET();
    /* 2 ms gives the peripheral time to come back up cleanly after the RCC
       reset. vTaskDelay (vs HAL_Delay) yields the CPU so the UI task can
       render a frame instead of busy-waiting. */
    vTaskDelay(pdMS_TO_TICKS(2));
}

/* Try to mount. Caller must hold s_fatfs_mutex. On success, populates
   s_next_index for future create calls. */
static bool try_mount_locked(void)
{
    /* Full HAL_SD teardown before mount — see reset_sd_hal() comment. */
    reset_sd_hal();

    /* SDPath is the drive prefix the SD driver was linked with — typically
       "" for the only volume. Using the actual variable instead of a hard-
       coded "" keeps us aligned with whatever CubeMX picked. */
    FRESULT r = f_mount(&SDFatFS, SDPath, 1);   /* 1 = force mount now */
    if (r != FR_OK) return false;

    uint16_t next = 1;
    (void)scan_highest_index_locked(&next);     /* best-effort; safe to ignore on FR_NO_FILESYSTEM etc. */
    s_next_index = next;
    return true;
}

/* Caller must hold s_fatfs_mutex. */
static void try_unmount_locked(void)
{
    /* f_mount(NULL, ...) unregisters the FATFS object so a remount on
       re-insert starts clean (FAT/dir cache invalidated). */
    f_mount(NULL, SDPath, 0);
}

void sd_card_lock(void)
{
    if (s_fatfs_mutex) xSemaphoreTake(s_fatfs_mutex, portMAX_DELAY);
}

void sd_card_unlock(void)
{
    if (s_fatfs_mutex) xSemaphoreGive(s_fatfs_mutex);
}

void sd_card_init(void)
{
    s_mounted    = false;
    s_next_index = 1;
    /* Priority-inheriting mutex so a lower-priority task holding it gets
       boosted to the priority of whoever's waiting. Recorder, player, UI
       file-list refresh, and the poll task all contend for this — without
       inheritance, a 50 ms file scan in the UI thread could end up behind
       a recorder write that just got preempted by a UI-priority task. */
    s_fatfs_mutex = xSemaphoreCreateMutex();

    if (BSP_PlatformIsDetected() != SD_NOT_PRESENT) {
        sd_card_lock();
        s_mounted = try_mount_locked();
        sd_card_unlock();
    }
}

bool sd_card_mounted(void)
{
    return s_mounted;
}

/* Forcibly unblock any task currently inside f_write/f_read by aborting
   the in-flight SDMMC DMA. HAL_SD_Abort_IT calls HAL_SD_AbortCallback →
   BSP_SD_AbortCallback (overridden in sd_diskio.c USER CODE block) which
   pushes a non-CPLT message into the diskio queue. The blocked task wakes,
   sees the unexpected message, returns RES_ERROR → FR_DISK_ERR propagates
   up to recorder/player. */
static void abort_inflight_dma(void)
{
    (void)HAL_SD_Abort_IT(&hsd1);
}

/* Drain stale messages from the sd_diskio queue. Provided by the USER CODE
   block in [FATFS/Target/sd_diskio.c]. Called after the FATFS mutex is held
   (so no SD_read/SD_write is in flight) and before re-mount can occur. */
extern void sd_diskio_drain_queue(void);

/* Card-removal path. UI sees s_mounted=false within one poll tick; the
   slow FATFS cleanup completes asynchronously after recorder/player drain
   their state. Sequence matters:
     1. Flip s_mounted=false so the UI's next refresh_file_list skips f_opendir.
     2. Tell recorder/player to stop. They may be blocked in f_write/f_read.
     3. Abort the in-flight DMA so those blocked tasks return promptly.
     4. Take the mutex (blocks until recorder/player release it post-error).
     5. Unregister the volume so a re-insert remounts cleanly. */
static void handle_removal(void)
{
    s_mounted = false;

    recorder_stop();
    player_stop();

    abort_inflight_dma();

    /* Wait for recorder/player to release the mutex. The 2-second bound is
       SD_TIMEOUT (1500 ms per [sd_diskio.c override]) + a margin; if they
       can't release it in that window, something's deeply wrong and we
       leak the unmount — UI still shows no-card so the user can recover
       by re-inserting (the re-insert mount path also takes the mutex,
       which will eventually succeed). */
    if (s_fatfs_mutex
        && xSemaphoreTake(s_fatfs_mutex, pdMS_TO_TICKS(2500)) == pdTRUE) {
        try_unmount_locked();
        /* If no task was blocked in osMessageQueueGet at the moment of
           abort, the 0xFFFF message we pushed sits in the queue. Drain
           it now so the next FATFS operation after re-insert doesn't
           grab it as a spurious error. */
        sd_diskio_drain_queue();
        xSemaphoreGive(s_fatfs_mutex);
    }
}

bool sd_card_poll(void)
{
    bool present = (BSP_PlatformIsDetected() != SD_NOT_PRESENT);
    if (present && !s_mounted) {
        sd_card_lock();
        s_mounted = try_mount_locked();
        sd_card_unlock();
        return s_mounted;
    }
    if (!present && s_mounted) {
        handle_removal();
        return true;
    }
    return false;
}

bool sd_card_next_filename(char *out)
{
    if (!s_mounted) return false;
    if (s_next_index > 999) return false;

    /* No printf — go straight to digits. snprintf works too but bloats
       binary by ~2 KB once newlib formatting is referenced. */
    out[0] = 'R';
    out[1] = 'E';
    out[2] = 'C';
    uint16_t n = s_next_index;
    out[3] = (char)('0' + (n / 100) % 10);
    out[4] = (char)('0' + (n / 10)  % 10);
    out[5] = (char)('0' + (n)       % 10);
    out[6] = '.';
    out[7] = 'W';
    out[8] = 'A';
    out[9] = 'V';
    out[10] = '\0';
    s_next_index++;
    return true;
}

bool sd_card_scan_recordings(char list[][SD_REC_FILENAME_MAX], int max, int *count)
{
    *count = 0;
    if (!s_mounted || max <= 0) return s_mounted;

    DIR     dir;
    FILINFO fno;

    sd_card_lock();

    /* Re-check mount under the lock — a concurrent yank may have flipped
       s_mounted between the early-return above and now. */
    if (!s_mounted) {
        sd_card_unlock();
        return false;
    }

    if (f_opendir(&dir, "/") != FR_OK) {
        sd_card_unlock();
        return s_mounted;
    }

    /* Keep a sliding window of the highest 'max' indices we've seen.
       Implemented as a tiny insertion sort — O(n*max), trivial for a few
       hundred files at UI-call rate. */
    int      n = 0;
    uint16_t idx_buf[8];                       /* matches the UI's max list slot count */
    char     name_buf[8][SD_REC_FILENAME_MAX];
    if (max > 8) max = 8;

    for (;;) {
        if (f_readdir(&dir, &fno) != FR_OK || fno.fname[0] == 0) break;
        if (fno.fattrib & AM_DIR) continue;
        int idx = parse_rec_index(fno.fname);
        if (idx <= 0) continue;

        if (n < max) {
            idx_buf[n] = (uint16_t)idx;
            strncpy(name_buf[n], fno.fname, SD_REC_FILENAME_MAX - 1);
            name_buf[n][SD_REC_FILENAME_MAX - 1] = '\0';
            n++;
        } else {
            /* Find the smallest idx in our buffer; replace it if this one is higher. */
            int min_pos = 0;
            for (int i = 1; i < n; i++) {
                if (idx_buf[i] < idx_buf[min_pos]) min_pos = i;
            }
            if ((uint16_t)idx > idx_buf[min_pos]) {
                idx_buf[min_pos] = (uint16_t)idx;
                strncpy(name_buf[min_pos], fno.fname, SD_REC_FILENAME_MAX - 1);
                name_buf[min_pos][SD_REC_FILENAME_MAX - 1] = '\0';
            }
        }
    }
    f_closedir(&dir);

    sd_card_unlock();

    /* Selection-sort the buffer by index ascending (oldest first for display).
       Done outside the lock — purely operating on local arrays. */
    for (int i = 0; i < n - 1; i++) {
        int min_pos = i;
        for (int j = i + 1; j < n; j++) {
            if (idx_buf[j] < idx_buf[min_pos]) min_pos = j;
        }
        if (min_pos != i) {
            uint16_t ti = idx_buf[i]; idx_buf[i] = idx_buf[min_pos]; idx_buf[min_pos] = ti;
            char tn[SD_REC_FILENAME_MAX];
            memcpy(tn,             name_buf[i],       SD_REC_FILENAME_MAX);
            memcpy(name_buf[i],    name_buf[min_pos], SD_REC_FILENAME_MAX);
            memcpy(name_buf[min_pos], tn,             SD_REC_FILENAME_MAX);
        }
    }

    for (int i = 0; i < n; i++) {
        memcpy(list[i], name_buf[i], SD_REC_FILENAME_MAX);
    }
    *count = n;
    return s_mounted;
}
