#include "sd_card.h"
#include "fatfs.h"
#include "ff.h"
#include "fatfs_platform.h"
#include <string.h>

/* SDFatFS, SDPath, retSD all live in FATFS/App/fatfs.c (generated by
   CubeMX). MX_FATFS_Init() has already called FATFS_LinkDriver() before
   we run, so f_mount can use the empty drive prefix immediately. */
extern FATFS SDFatFS;
extern char  SDPath[4];

static volatile bool s_mounted;
static uint16_t      s_next_index;   /* next index for sd_card_next_filename */

/* Parse "RECNNN.WAV" → index, or return -1 if the name doesn't match.
   Lookups are case-sensitive against the uppercase form we always emit;
   FAT32 short-name entries are uppercased by the filesystem on write, so
   a freshly-written file always reads back uppercase. */
static int parse_rec_index(const char *name)
{
    if (name[0] != 'R' || name[1] != 'E' || name[2] != 'C') return -1;
    int idx = 0;
    int digits = 0;
    int i = 3;
    while (name[i] >= '0' && name[i] <= '9' && digits < 4) {
        idx = idx * 10 + (name[i] - '0');
        i++;
        digits++;
    }
    if (digits == 0) return -1;
    if (name[i] != '.') return -1;
    if (name[i+1] != 'W' || name[i+2] != 'A' || name[i+3] != 'V') return -1;
    if (name[i+4] != '\0') return -1;
    return idx;
}

/* Walk the root directory, track the highest REC index seen. Called at
   mount and from sd_card_next_filename() to pick the next slot. */
static FRESULT scan_highest_index(uint16_t *out_next)
{
    DIR  dir;
    FILINFO fno;
    int highest = 0;

    FRESULT r = f_opendir(&dir, "/");
    if (r != FR_OK) return r;

    for (;;) {
        r = f_readdir(&dir, &fno);
        if (r != FR_OK || fno.fname[0] == 0) break;
        if (fno.fattrib & AM_DIR) continue;
        int idx = parse_rec_index(fno.fname);
        if (idx > highest) highest = idx;
    }
    f_closedir(&dir);

    *out_next = (uint16_t)(highest + 1);
    return FR_OK;
}

/* Try to mount. On success, populates s_next_index for future create calls. */
static bool try_mount(void)
{
    /* SDPath is the drive prefix the SD driver was linked with — typically
       "" for the only volume. Using the actual variable instead of a hard-
       coded "" keeps us aligned with whatever CubeMX picked. */
    FRESULT r = f_mount(&SDFatFS, SDPath, 1);   /* 1 = force mount now */
    if (r != FR_OK) return false;

    uint16_t next = 1;
    (void)scan_highest_index(&next);            /* best-effort; safe to ignore on FR_NO_FILESYSTEM etc. */
    s_next_index = next;
    return true;
}

static void try_unmount(void)
{
    /* f_mount(NULL, ...) unregisters the FATFS object so a remount on
       re-insert starts clean (FAT/dir cache invalidated). */
    f_mount(NULL, SDPath, 0);
}

void sd_card_init(void)
{
    s_mounted    = false;
    s_next_index = 1;
    if (BSP_PlatformIsDetected() != SD_NOT_PRESENT) {
        s_mounted = try_mount();
    }
}

bool sd_card_mounted(void)
{
    return s_mounted;
}

bool sd_card_poll(void)
{
    bool present = (BSP_PlatformIsDetected() != SD_NOT_PRESENT);
    if (present && !s_mounted) {
        s_mounted = try_mount();
        return s_mounted;
    }
    if (!present && s_mounted) {
        try_unmount();
        s_mounted = false;
        return true;
    }
    return false;
}

bool sd_card_next_filename(char *out)
{
    if (!s_mounted) return false;
    if (s_next_index > 999) return false;

    /* No printf — go straight to digits. snprintf works too but bloats
       binary by ~2 KB once newlib formatting is referenced. */
    out[0] = 'R';
    out[1] = 'E';
    out[2] = 'C';
    uint16_t n = s_next_index;
    out[3] = (char)('0' + (n / 100) % 10);
    out[4] = (char)('0' + (n / 10)  % 10);
    out[5] = (char)('0' + (n)       % 10);
    out[6] = '.';
    out[7] = 'W';
    out[8] = 'A';
    out[9] = 'V';
    out[10] = '\0';
    s_next_index++;
    return true;
}

bool sd_card_scan_recordings(char list[][SD_REC_FILENAME_MAX], int max, int *count)
{
    *count = 0;
    if (!s_mounted || max <= 0) return s_mounted;

    DIR     dir;
    FILINFO fno;

    if (f_opendir(&dir, "/") != FR_OK) return s_mounted;

    /* Keep a sliding window of the highest 'max' indices we've seen.
       Implemented as a tiny insertion sort — O(n*max), trivial for a few
       hundred files at UI-call rate. */
    int      n = 0;
    uint16_t idx_buf[8];                       /* matches the UI's max list slot count */
    char     name_buf[8][SD_REC_FILENAME_MAX];
    if (max > 8) max = 8;

    for (;;) {
        if (f_readdir(&dir, &fno) != FR_OK || fno.fname[0] == 0) break;
        if (fno.fattrib & AM_DIR) continue;
        int idx = parse_rec_index(fno.fname);
        if (idx <= 0) continue;

        if (n < max) {
            idx_buf[n] = (uint16_t)idx;
            strncpy(name_buf[n], fno.fname, SD_REC_FILENAME_MAX - 1);
            name_buf[n][SD_REC_FILENAME_MAX - 1] = '\0';
            n++;
        } else {
            /* Find the smallest idx in our buffer; replace it if this one is higher. */
            int min_pos = 0;
            for (int i = 1; i < n; i++) {
                if (idx_buf[i] < idx_buf[min_pos]) min_pos = i;
            }
            if ((uint16_t)idx > idx_buf[min_pos]) {
                idx_buf[min_pos] = (uint16_t)idx;
                strncpy(name_buf[min_pos], fno.fname, SD_REC_FILENAME_MAX - 1);
                name_buf[min_pos][SD_REC_FILENAME_MAX - 1] = '\0';
            }
        }
    }
    f_closedir(&dir);

    /* Selection-sort the buffer by index ascending (oldest first for display). */
    for (int i = 0; i < n - 1; i++) {
        int min_pos = i;
        for (int j = i + 1; j < n; j++) {
            if (idx_buf[j] < idx_buf[min_pos]) min_pos = j;
        }
        if (min_pos != i) {
            uint16_t ti = idx_buf[i]; idx_buf[i] = idx_buf[min_pos]; idx_buf[min_pos] = ti;
            char tn[SD_REC_FILENAME_MAX];
            memcpy(tn,             name_buf[i],       SD_REC_FILENAME_MAX);
            memcpy(name_buf[i],    name_buf[min_pos], SD_REC_FILENAME_MAX);
            memcpy(name_buf[min_pos], tn,             SD_REC_FILENAME_MAX);
        }
    }

    for (int i = 0; i < n; i++) {
        memcpy(list[i], name_buf[i], SD_REC_FILENAME_MAX);
    }
    *count = n;
    return s_mounted;
}
