#!/usr/bin/env python3
"""Embed a .tflite (or any binary) into a C source file as a byte array.

Invoked from the top-level CMakeLists.txt to turn Models/*.tflite into the
generated .cc files that the wake-word path links against. Pure stdlib so it
runs anywhere Python 3 is installed.

Usage:
  embed_model.py <input.bin> <output.cc> <variable_name>
"""

import os
import sys


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 1

    inp_path, out_path, var = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(inp_path, "rb") as f:
        data = f.read()

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "/* Auto-generated by tools/embed_model.py from "
            f"{os.path.basename(inp_path)}.\n"
            f" * Size: {len(data)} bytes. Do not edit by hand. */\n\n"
        )
        f.write("#include <stdint.h>\n\n")
        f.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
        # 16-byte alignment: TFLite FlatBuffer access wants at least 4-byte
        # alignment; 16 gives headroom and matches what TFLM examples use.
        #
        # `extern` is load-bearing: in C++, top-level `const` defaults to
        # internal linkage. `extern "C"` only controls name mangling. Without
        # the explicit extern keyword, the symbol stays file-local and the
        # consumer .cc gets an undefined reference at link time.
        f.write(
            "__attribute__((aligned(16))) "
            f"extern const unsigned char {var}[] = {{\n"
        )
        for i in range(0, len(data), 16):
            chunk = data[i : i + 16]
            f.write("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        f.write("};\n\n")
        f.write(f"extern const unsigned int {var}_len = {len(data)};\n\n")
        f.write("#ifdef __cplusplus\n}\n#endif\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
